language: node_js

node_js:
  - '10'

services:
  - docker
script:
  - bash ./scripts/docker_push.sh

deploy:
  - provider: script
    script: bash ./scripts/docker_push.sh
    on:
      branch: fix-docker-build
  - provider: script
    script: bash ./scripts/docker_push.sh
    on:
      branch: develop
  - provider: script
    script: bash ./scripts/docker_push.sh
    on:
      branch: master
