language: node_js

node_js:
  - "10"

services:
  - docker

before_install:
  - docker build "$DOCKER_USERNAME"/centrifuge-ui-kit .

deploy:
  provider: script
  script: bash ./scripts/docker_push.sh
  on:
    branch: travis-docker